//go:build !ignore_autogenerated

/*
Copyright 2026 fei232401.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.
// 注意: controller-gen v0.16.5 在 go1.26 下只生成了 root 类型方法, 嵌套类型方法由人工补齐
// (标准 kubebuilder 项目此文件应完全由 controller-gen 生成)

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingPolicy) DeepCopyInto(out *RoutingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, creating a new RoutingPolicy.
func (in *RoutingPolicy) DeepCopy() *RoutingPolicy {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *RoutingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies RoutingPolicyList.
func (in *RoutingPolicyList) DeepCopyInto(out *RoutingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoutingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new RoutingPolicyList.
func (in *RoutingPolicyList) DeepCopy() *RoutingPolicyList {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *RoutingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies RoutingPolicySpec.
func (in *RoutingPolicySpec) DeepCopyInto(out *RoutingPolicySpec) {
	*out = *in
	out.Rollout = in.Rollout
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.SLO = in.SLO
}

// DeepCopy creates a new RoutingPolicySpec.
func (in *RoutingPolicySpec) DeepCopy() *RoutingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies RolloutSpec.
func (in *RolloutSpec) DeepCopyInto(out *RolloutSpec) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy creates a new RolloutSpec.
func (in *RolloutSpec) DeepCopy() *RolloutSpec {
	if in == nil {
		return nil
	}
	out := new(RolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies Rule.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	out.Condition = in.Condition
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy creates a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ConditionSpec.
func (in *ConditionSpec) DeepCopyInto(out *ConditionSpec) {
	*out = *in
}

// DeepCopy creates a new ConditionSpec.
func (in *ConditionSpec) DeepCopy() *ConditionSpec {
	if in == nil {
		return nil
	}
	out := new(ConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ActionSpec.
func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	if in.FallbackChain != nil {
		in, out := &in.FallbackChain, &out.FallbackChain
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a new ActionSpec.
func (in *ActionSpec) DeepCopy() *ActionSpec {
	if in == nil {
		return nil
	}
	out := new(ActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SLOSpec.
func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
}

// DeepCopy creates a new SLOSpec.
func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies SLOTier.
func (in *SLOTier) DeepCopyInto(out *SLOTier) {
	*out = *in
}

// DeepCopy creates a new SLOTier.
func (in *SLOTier) DeepCopy() *SLOTier {
	if in == nil {
		return nil
	}
	out := new(SLOTier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies RoutingPolicyStatus.
func (in *RoutingPolicyStatus) DeepCopyInto(out *RoutingPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new RoutingPolicyStatus.
func (in *RoutingPolicyStatus) DeepCopy() *RoutingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RoutingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
