grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: ClusterIP
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"

prometheus:
  prometheusSpec:
    externalUrl: http://localhost/prometheus
    routePrefix: /
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
